name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd front
          npm ci

      - name: Build project
        run: |
          cd front
          npm run build

      # Ajoute ici ton étape de déploiement (ex: vers GitHub Pages, FTP, etc.)
      # Exemple pour GitHub Pages (si tu utilises vite-plugin-gh-pages ou autre):
      # - name: Deploy to GitHub Pages
      #   run: |
      #     cd front
      #     npm run deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Sinon, adapte selon ta cible de déploiement
